server:
  port: 8080

resteasy:
  deployment:
    async_job_service_enabled: true
---
spring:
  profiles: test
  datasource:
    username: sa
    url: jdbc:h2:./data/keycloak
    driver-class-name: org.h2.Driver
keycloak:
  server:
    contextPath: /auth
    importRealms: import-realm.json
---
spring:
  profiles: mysql
---
spring:
  profiles: cloud
  datasource:
    username: ${cloud.services.mysql.connection.username}
    password: ${cloud.services.mysql.connection.password}
    url: ${cloud.services.mysql.connection.jdbcUrl}
    driver-class-name: com.mysql.jdbc.Driver
#    hikari:
#      pool-name: SpringBootHikariCP
#      maximum-pool-size: 20
#      minimum-idle: 3
#      max-lifetime: 2000000
#      connection-timeout: 30000
#      idle-timeout: 30000
#      allow-pool-suspension: true
#    type: com.zaxxer.hikari.HikariDataSource

keycloak:
  server:
    connections-jpa-driver: com.mysql.jdbc.Driver
    connections-jpa-driver-dialect: org.hibernate.dialect.MySQLDialect
---